this was for like nasty show not like nastya

# In this notebook we are going to calculate the values for december 2024

In [ ]:
import pandas as pd
top_kids_monthly = pd.read_csv('/content/top_kids_mothly.csv')
like_nastya_per_day = pd.read_csv('/content/like_nastya_per_day.csv')

In [ ]:
like_nastya_per_day

,date,subs,views,estimated_earning,min_earning_dol,max_earning_dol,mean_earning_dol
0,2024-12-11,44100000.0,2.116725e+10,"$4,234.54 - $12,703.61",4234.54,12703.61,8469.075
1,2024-12-10,44100000.0,2.116481e+10,"$3,927.23 - $11,781.7",3927.23,11781.70,7854.465
2,2024-12-09,44100000.0,2.116255e+10,"$4,701.78 - $14,105.35",4701.78,14105.35,9403.565
3,2024-12-08,44100000.0,2.115984e+10,"$5,028.5 - $15,085.51",5028.50,15085.51,10057.005
4,2024-12-07,44100000.0,2.115694e+10,"$3,795.39 - $11,386.17",3795.39,11386.17,7590.780
5,2024-12-06,44100000.0,2.115475e+10,"$2,208.54 - $6,625.61",2208.54,6625.61,4417.075
6,2024-12-05,44100000.0,2.115348e+10,"$5,328.62 - $15,985.86",5328.62,15985.86,10657.240
7,2024-12-04,44100000.0,2.115041e+10,"$3,892.49 - $11,677.46",3892.49,11677.46,7784.975
8,2024-12-03,44100000.0,2.114816e+10,"$3,471.75 - $10,415.25",3471.75,10415.25,6943.500
9,2024-12-02,44100000.0,2.114616e+10,"$4,055.09 - $12,165.28",4055.09,12165.28,8110.185
10,2024-12-01,44100000.0,2.114382e+10,"$4,210.28 - $12,630.83",4210.28,12630.83,8420.555
11,2024-11-30,44100000.0,2.114140e+10,"$4,044.79 - $12,134.36",4044.79,12134.36,8089.575
12,2024-11-29,44100000.0,2.113907e+10,"$4,305.62 - $12,916.85",4305.62,12916.85,8611.235
13,2024-11-28,44100000.0,2.113658e+10,"$4,305.43 - $12,916.29",4305.43,12916.29,8610.860
14,2024-11-27,44100000.0,2.113410e+10,"$3,760.6 - $11,281.81",3760.60,11281.81,7521.205
15,2024-11-26,44100000.0,2.113194e+10,"$3,776.37 - $11,329.11",3776.37,11329.11,7552.740
16,2024-11-25,44100000.0,2.112976e+10,"$4,232.93 - $12,698.79",4232.93,12698.79,8465.860
17,2024-11-24,44100000.0,2.112732e+10,"$4,446.97 - $13,340.9",4446.97,13340.90,8893.935
18,2024-11-23,44100000.0,2.112476e+10,"$3,946.2 - $11,838.61",3946.20,11838.61,7892.405
19,2024-11-22,44100000.0,2.112248e+10,"$4,046.31 - $12,138.92",4046.31,12138.92,8092.615
20,2024-11-21,44100000.0,2.112015e+10,"$4,087 - $12,260.99",4087.00,12260.99,8173.995
21,2024-11-20,44100000.0,2.111779e+10,"$4,097.97 - $12,293.92",4097.97,12293.92,8195.945
22,2024-11-19,44100000.0,2.111543e+10,"$4,551.73 - $13,655.18",4551.73,13655.18,9103.455
23,2024-11-18,44100000.0,2.111281e+10,"$5,537.18 - $16,611.55",5537.18,16611.55,11074.365
24,2024-11-17,44100000.0,2.110962e+10,"$6,236.95 - $18,710.85",6236.95,18710.85,12473.900
25,2024-11-16,44100000.0,2.110602e+10,"$5,698.08 - $17,094.23",5698.08,17094.23,11396.155
26,2024-11-15,44100000.0,2.110274e+10,"$6,889.58 - $20,668.73",6889.58,20668.73,13779.155
27,2024-11-14,44100000.0,2.109877e+10,"$8,640.27 - $25,920.82",8640.27,25920.82,17280.545
28,2024-11-13,44100000.0,2.109379e+10,"$8,023.38 - $24,070.15",8023.38,24070.15,16046.765
29,2024-11-12,44100000.0,2.108916e+10,"$8,103.35 - $24,310.05",8103.35,24310.05,16206.700

# We are going to start with Like Nastya channel


**Convert date columns to datetime**

In [ ]:
top_kids_monthly['date'] = pd.to_datetime(top_kids_monthly['date'])
like_nastya_per_day['date'] = pd.to_datetime(like_nastya_per_day['date'])

# Process the Daily Data for December for Like Nastya
Extract December data and calculate the total earnings for December 1–11.

In [ ]:
# Filter December data
december_data = like_nastya_per_day[
    (like_nastya_per_day['date'] >= '2024-12-01') & (like_nastya_per_day['date'] <= '2024-12-11')
]

# Calculate total earnings for December 1–11
dec_1_11_earnings = december_data['mean_earning_dol'].sum()

In [ ]:
dec_1_11_earnings

89708.41999999998

**We have our number for 1-11 December, let's estimate the 12-31 values**

# Calculate the Daily Average for 2024 (Excluding December) for all the table
Use data from January to November 2024 to calculate the daily average earnings.

In [ ]:
# filter 2024 data excluding December
completed_months_2024 = top_kids_monthly[
    (top_kids_monthly['date'] < '2024-12-01') & (top_kids_monthly['date'] >= '2024-01-01')
]

# add the number of days in each month
completed_months_2024['days_in_month'] = completed_months_2024['date'].dt.days_in_month

# calculate the DAILY average earnings for each month
completed_months_2024['daily_average'] = completed_months_2024['estimation_earning_numeric'] / completed_months_2024['days_in_month']

# Compute the overall daily average earnings for 2024 (excluding December)
overall_daily_average = completed_months_2024['daily_average'].mean()

overall_daily_average

<ipython-input-5-0f0aea46b618>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_months_2024['days_in_month'] = completed_months_2024['date'].dt.days_in_month
<ipython-input-5-0f0aea46b618>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_months_2024['daily_average'] = completed_months_2024['estimation_earning_numeric'] / completed_months_2024['days_in_month']

35545.209087538344

In [ ]:
completed_months_2024

,date,estimation_earning,estimation_earning_numeric,youtuber,days_in_month,daily_average
0,2024-11-01,2.74M,2740000.0,Toys_and_Colors,30,91333.333333
1,2024-10-01,2.98M,2980000.0,Toys_and_Colors,31,96129.032258
2,2024-09-01,2.64M,2640000.0,Toys_and_Colors,30,88000.000000
3,2024-08-01,2.48M,2480000.0,Toys_and_Colors,31,80000.000000
4,2024-07-01,2.02M,2020000.0,Toys_and_Colors,31,65161.290323
5,2024-06-01,2.3M,2300000.0,Toys_and_Colors,30,76666.666667
6,2024-05-01,1.77M,1770000.0,Toys_and_Colors,31,57096.774194
7,2024-04-01,1.85M,1850000.0,Toys_and_Colors,30,61666.666667
8,2024-03-01,1.79M,1790000.0,Toys_and_Colors,31,57741.935484
9,2024-02-01,1.65M,1650000.0,Toys_and_Colors,29,56896.551724
10,2024-01-01,934K,934000.0,Toys_and_Colors,31,30129.032258
22,2024-11-01,1.32M,1320000.0,Vlad_and_Niki,30,44000.000000
23,2024-10-01,1.13M,1130000.0,Vlad_and_Niki,31,36451.612903
24,2024-09-01,1.23M,1230000.0,Vlad_and_Niki,30,41000.000000
25,2024-08-01,1.38M,1380000.0,Vlad_and_Niki,31,44516.129032
26,2024-07-01,1.03M,1030000.0,Vlad_and_Niki,31,33225.806452
27,2024-06-01,1.41M,1410000.0,Vlad_and_Niki,30,47000.000000
28,2024-05-01,1.06M,1060000.0,Vlad_and_Niki,31,34193.548387
29,2024-04-01,1.7M,1700000.0,Vlad_and_Niki,30,56666.666667
30,2024-03-01,1.66M,1660000.0,Vlad_and_Niki,31,53548.387097
31,2024-02-01,2.16M,2160000.0,Vlad_and_Niki,29,74482.758621
32,2024-01-01,993K,993000.0,Vlad_and_Niki,31,32032.258065
46,2024-11-01,109K,109000.0,Like_Nastya_Show,30,3633.333333
47,2024-05-01,110K,110000.0,Like_Nastya_Show,31,3548.387097
48,2024-07-01,120K,120000.0,Like_Nastya_Show,31,3870.967742
49,2024-06-01,132K,132000.0,Like_Nastya_Show,30,4400.000000
51,2024-09-01,141K,141000.0,Like_Nastya_Show,30,4700.000000
55,2024-04-01,61.1K,61100.0,Like_Nastya_Show,30,2036.666667
56,2024-01-01,62.6K,62600.0,Like_Nastya_Show,31,2019.354839
60,2024-03-01,82.5K,82500.0,Like_Nastya_Show,31,2661.290323
62,2024-08-01,86.2K,86200.0,Like_Nastya_Show,31,2780.645161
63,2024-10-01,87.2K,87200.0,Like_Nastya_Show,31,2812.903226
65,2024-02-01,95.4K,95400.0,Like_Nastya_Show,29,3289.655172
66,2024-11-01,1.17M,1170000.0,Like_Nastya,30,39000.000000
67,2024-10-01,863K,863000.0,Like_Nastya,31,27838.709677
68,2024-09-01,981K,981000.0,Like_Nastya,30,32700.000000
69,2024-08-01,1.42M,1420000.0,Like_Nastya,31,45806.451613
70,2024-07-01,970K,970000.0,Like_Nastya,31,31290.322581
71,2024-06-01,1.01M,1010000.0,Like_Nastya,30,33666.666667
72,2024-05-01,818K,818000.0,Like_Nastya,31,26387.096774
73,2024-04-01,831K,831000.0,Like_Nastya,30,27700.000000
74,2024-03-01,927K,927000.0,Like_Nastya,31,29903.225806
75,2024-02-01,980K,980000.0,Like_Nastya,29,33793.103448
76,2024-01-01,602K,602000.0,Like_Nastya,31,19419.354839
89,2024-08-01,601K,601000.0,Kids_Diana_Show,31,19387.096774
90,2024-07-01,672K,672000.0,Kids_Diana_Show,31,21677.419355
91,2024-01-01,707K,707000.0,Kids_Diana_Show,31,22806.451613
92,2024-09-01,715K,715000.0,Kids_Diana_Show,30,23833.333333
94,2024-04-01,794K,794000.0,Kids_Diana_Show,30,26466.666667
96,2024-06-01,827K,827000.0,Kids_Diana_Show,30,27566.666667
97,2024-10-01,835K,835000.0,Kids_Diana_Show,31,26935.483871
99,2024-03-01,917K,917000.0,Kids_Diana_Show,31,29580.645161
101,2024-05-01,1.03M,1030000.0,Kids_Diana_Show,31,33225.806452
104,2024-02-01,1.14M,1140000.0,Kids_Diana_Show,29,39310.344828
107,2024-11-01,1.29M,1290000.0,Kids_Diana_Show,30,43000.000000

# Add the Number of Days in Each Month

In [ ]:
# Add a column for days in each month
top_kids_monthly['days_in_month'] = top_kids_monthly['date'].dt.days_in_month

# Calculate Average Daily Earnings for Each Month

In [ ]:
# Calculate average daily earnings for each channel
top_kids_monthly['daily_average_earning'] = (
    top_kids_monthly['estimation_earning_numeric'] / top_kids_monthly['days_in_month']
)

# Calculate Earnings for 20 Days for Each Month

In [ ]:
# Calculate earnings for 20 days
top_kids_monthly['20_day_earning'] = top_kids_monthly['daily_average_earning'] * 20

In [ ]:
top_kids_monthly.head(100)

,date,estimation_earning,estimation_earning_numeric,youtuber,days_in_month,daily_average_earning,20_day_earning
0,2024-11-01,2.74M,2740000.0,Toys_and_Colors,30,91333.333333,1.826667e+06
1,2024-10-01,2.98M,2980000.0,Toys_and_Colors,31,96129.032258,1.922581e+06
2,2024-09-01,2.64M,2640000.0,Toys_and_Colors,30,88000.000000,1.760000e+06
3,2024-08-01,2.48M,2480000.0,Toys_and_Colors,31,80000.000000,1.600000e+06
4,2024-07-01,2.02M,2020000.0,Toys_and_Colors,31,65161.290323,1.303226e+06
...,...,...,...,...,...,...,...
95,2023-06-01,794K,794000.0,Kids_Diana_Show,30,26466.666667,5.293333e+05
96,2024-06-01,827K,827000.0,Kids_Diana_Show,30,27566.666667,5.513333e+05
97,2024-10-01,835K,835000.0,Kids_Diana_Show,31,26935.483871,5.387097e+05
98,2022-12-01,915K,915000.0,Kids_Diana_Show,31,29516.129032,5.903226e+05
99,2024-03-01,917K,917000.0,Kids_Diana_Show,31,29580.645161,5.916129e+05

# Calculate Average 20-Day Earnings for 11 Months

In [ ]:
# Filter data for "Like Nastya" (replace with the specific column name if needed)
like_nastya_data = top_kids_monthly[top_kids_monthly['youtuber'] == 'Like_Nastya_Show']
like_nastya_data

,date,estimation_earning,estimation_earning_numeric,youtuber,days_in_month,daily_average_earning,20_day_earning
44,2023-11-01,100K,100000.0,Like_Nastya_Show,30,3333.333333,66666.666667
45,2023-02-01,103K,103000.0,Like_Nastya_Show,28,3678.571429,73571.428571
46,2024-11-01,109K,109000.0,Like_Nastya_Show,30,3633.333333,72666.666667
47,2024-05-01,110K,110000.0,Like_Nastya_Show,31,3548.387097,70967.741935
48,2024-07-01,120K,120000.0,Like_Nastya_Show,31,3870.967742,77419.354839
49,2024-06-01,132K,132000.0,Like_Nastya_Show,30,4400.000000,88000.000000
50,2023-01-01,132K,132000.0,Like_Nastya_Show,31,4258.064516,85161.290323
51,2024-09-01,141K,141000.0,Like_Nastya_Show,30,4700.000000,94000.000000
52,2023-07-01,49.7K,49700.0,Like_Nastya_Show,31,1603.225806,32064.516129
53,2023-06-01,51.2K,51200.0,Like_Nastya_Show,30,1706.666667,34133.333333
54,2023-12-01,60.9K,60900.0,Like_Nastya_Show,31,1964.516129,39290.322581
55,2024-04-01,61.1K,61100.0,Like_Nastya_Show,30,2036.666667,40733.333333
56,2024-01-01,62.6K,62600.0,Like_Nastya_Show,31,2019.354839,40387.096774
57,2023-04-01,64.3K,64300.0,Like_Nastya_Show,30,2143.333333,42866.666667
58,2023-05-01,65.6K,65600.0,Like_Nastya_Show,31,2116.129032,42322.580645
59,2023-10-01,82.2K,82200.0,Like_Nastya_Show,31,2651.612903,53032.258065
60,2024-03-01,82.5K,82500.0,Like_Nastya_Show,31,2661.290323,53225.806452
61,2023-03-01,84.1K,84100.0,Like_Nastya_Show,31,2712.903226,54258.064516
62,2024-08-01,86.2K,86200.0,Like_Nastya_Show,31,2780.645161,55612.903226
63,2024-10-01,87.2K,87200.0,Like_Nastya_Show,31,2812.903226,56258.064516
64,2022-12-01,87.8K,87800.0,Like_Nastya_Show,31,2832.258065,56645.161290
65,2024-02-01,95.4K,95400.0,Like_Nastya_Show,29,3289.655172,65793.103448

In [ ]:
# Filter out December
like_nastya_2024_11_months = like_nastya_data[
    (like_nastya_data['date'] >= '2024-01-01') & (like_nastya_data['date'] < '2024-12-01')
]

# Calculate average 20-day earnings for the first 11 months of 2024
average_20_day_earning_like_nastya = like_nastya_2024_11_months['20_day_earning'].mean()

In [ ]:
average_20_day_earning_like_nastya

65005.824653655574

# Combine 20-Day Estimate with December 1–11 Earnings

In [ ]:
# Filter December 1–11 data
december_1_11_data = like_nastya_per_day[
    (like_nastya_per_day['date'] >= '2024-12-01') & (like_nastya_per_day['date'] <= '2024-12-11')
]

In [ ]:
december_1_11_data

,date,subs,views,estimated_earning,min_earning_dol,max_earning_dol,mean_earning_dol
0,2024-12-11,44100000.0,2.116725e+10,"$4,234.54 - $12,703.61",4234.54,12703.61,8469.075
1,2024-12-10,44100000.0,2.116481e+10,"$3,927.23 - $11,781.7",3927.23,11781.70,7854.465
2,2024-12-09,44100000.0,2.116255e+10,"$4,701.78 - $14,105.35",4701.78,14105.35,9403.565
3,2024-12-08,44100000.0,2.115984e+10,"$5,028.5 - $15,085.51",5028.50,15085.51,10057.005
4,2024-12-07,44100000.0,2.115694e+10,"$3,795.39 - $11,386.17",3795.39,11386.17,7590.780
5,2024-12-06,44100000.0,2.115475e+10,"$2,208.54 - $6,625.61",2208.54,6625.61,4417.075
6,2024-12-05,44100000.0,2.115348e+10,"$5,328.62 - $15,985.86",5328.62,15985.86,10657.240
7,2024-12-04,44100000.0,2.115041e+10,"$3,892.49 - $11,677.46",3892.49,11677.46,7784.975
8,2024-12-03,44100000.0,2.114816e+10,"$3,471.75 - $10,415.25",3471.75,10415.25,6943.500
9,2024-12-02,44100000.0,2.114616e+10,"$4,055.09 - $12,165.28",4055.09,12165.28,8110.185
10,2024-12-01,44100000.0,2.114382e+10,"$4,210.28 - $12,630.83",4210.28,12630.83,8420.555

In [ ]:

# Calculate total earnings for December 1–11
dec_1_11_earnings = december_1_11_data['mean_earning_dol'].sum()

# Combine the 20-day estimate with the December 1–11 earnings
total_december_earning_like_nastya = dec_1_11_earnings + average_20_day_earning_like_nastya

total_december_earning_like_nastya

154714.24465365557

# Update December Earnings in the top_kids_monthly DataFrame

In [ ]:
# Update the December 2024 earnings for "Like Nastya"
top_kids_monthly.loc[
    (top_kids_monthly['youtuber'] == 'Like_Nastya_Show') & (top_kids_monthly['date'] == '2024-12-01'),
    'estimation_earning_numeric'
] = total_december_earning_like_nastya

In [ ]:
top_kids_monthly

,date,estimation_earning,estimation_earning_numeric,youtuber,days_in_month,daily_average_earning,20_day_earning
0,2024-11-01,2.74M,2740000.0,Toys_and_Colors,30,91333.333333,1.826667e+06
1,2024-10-01,2.98M,2980000.0,Toys_and_Colors,31,96129.032258,1.922581e+06
2,2024-09-01,2.64M,2640000.0,Toys_and_Colors,30,88000.000000,1.760000e+06
3,2024-08-01,2.48M,2480000.0,Toys_and_Colors,31,80000.000000,1.600000e+06
4,2024-07-01,2.02M,2020000.0,Toys_and_Colors,31,65161.290323,1.303226e+06
...,...,...,...,...,...,...,...
105,2023-12-01,1.17M,1170000.0,Kids_Diana_Show,31,37741.935484,7.548387e+05
106,2023-11-01,1.28M,1280000.0,Kids_Diana_Show,30,42666.666667,8.533333e+05
107,2024-11-01,1.29M,1290000.0,Kids_Diana_Show,30,43000.000000,8.600000e+05
108,2023-03-01,1.65M,1650000.0,Kids_Diana_Show,31,53225.806452,1.064516e+06
109,2023-02-01,1.83M,1830000.0,Kids_Diana_Show,28,65357.142857,1.307143e+06

In [ ]:
december_2024_rows = top_kids_monthly[top_kids_monthly['date'] == '2024-12-01']
december_2024_rows

Empty DataFrame
Columns: [date, estimation_earning, estimation_earning_numeric, youtuber, days_in_month, daily_average_earning, 20_day_earning]
Index: []

In [ ]:
pandas as pd

# List of new per-day files and corresponding channel names
files_and_channels = [
    ('/content/Like_per_day.csv', 'Like_Nastya'),
    ('/content/Diana_Kids_Show_per_day.csv', 'Kids_Diana_Show'),
    ('/content/Toys_and_Colors_per_day.csv', 'Toys_and_Colors'),
    ('/content/Vlad_and_Niki.csv', 'Vlad_and_Niki')
]

# Function to process each channel's December earnings
def process_channel(file_path, channel_name):
    # Load the daily data
    daily_data = pd.read_csv(file_path)
    daily_data['date'] = pd.to_datetime(daily_data['date'])

    # Filter December 1–11 data
    december_1_11_data = daily_data[
        (daily_data['date'] >= '2024-12-01') & (daily_data['date'] <= '2024-12-11')
    ]
    dec_1_11_earnings = december_1_11_data['mean_earning_dol'].sum()

    # Filter the monthly data for the first 11 months of 2024
    channel_monthly = top_kids_monthly[
        (top_kids_monthly['youtuber'] == channel_name) &
        (top_kids_monthly['date'] >= '2024-01-01') &
        (top_kids_monthly['date'] < '2024-12-01')
    ]

    # Calculate daily average earnings and average 20-day earnings
    channel_monthly['daily_average_earning'] = (
        channel_monthly['estimation_earning_numeric'] / channel_monthly['days_in_month']
    )
    average_20_day_earning = channel_monthly['daily_average_earning'].mean() * 20

    # Combine December 1–11 actual earnings with estimated remaining earnings
    total_december_earning = dec_1_11_earnings + average_20_day_earning

    # Update the top_kids_monthly dataframe
    top_kids_monthly.loc[
        (top_kids_monthly['youtuber'] == channel_name) &
        (top_kids_monthly['date'] == '2024-12-01'),
        'estimation_earning_numeric'
    ] = total_december_earning

    print(f"Updated December earnings for {channel_name}: {total_december_earning}")

# Process all files and channels
for file_path, channel_name in files_and_channels:
    process_channel(file_path, channel_name)

# Save the updated top_kids_monthly dataset
top_kids_monthly.to_csv('/content/updated_top_kids_monthly.csv', index=False)

Updated December earnings for Like_Nastya: 2722209.548009573
Updated December earnings for Kids_Diana_Show: 570527.1176728351
Updated December earnings for Toys_and_Colors: 4746053.318467151
Updated December earnings for Vlad_and_Niki: 3120386.9699506187

<ipython-input-21-cb951c308e41>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  channel_monthly['daily_average_earning'] = (
<ipython-input-21-cb951c308e41>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  channel_monthly['daily_average_earning'] = (
<ipython-input-21-cb951c308e41>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  channel_monthly['daily_average_earning'] = (
<ipython-input-21-cb951c308e41>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  channel_monthly['daily_average_earning'] = (

In [ ]:
top_kids_monthly

,date,estimation_earning,estimation_earning_numeric,youtuber,days_in_month,daily_average_earning,20_day_earning
0,2024-11-01,2.74M,2740000.0,Toys_and_Colors,30,91333.333333,1.826667e+06
1,2024-10-01,2.98M,2980000.0,Toys_and_Colors,31,96129.032258,1.922581e+06
2,2024-09-01,2.64M,2640000.0,Toys_and_Colors,30,88000.000000,1.760000e+06
3,2024-08-01,2.48M,2480000.0,Toys_and_Colors,31,80000.000000,1.600000e+06
4,2024-07-01,2.02M,2020000.0,Toys_and_Colors,31,65161.290323,1.303226e+06
...,...,...,...,...,...,...,...
105,2023-12-01,1.17M,1170000.0,Kids_Diana_Show,31,37741.935484,7.548387e+05
106,2023-11-01,1.28M,1280000.0,Kids_Diana_Show,30,42666.666667,8.533333e+05
107,2024-11-01,1.29M,1290000.0,Kids_Diana_Show,30,43000.000000,8.600000e+05
108,2023-03-01,1.65M,1650000.0,Kids_Diana_Show,31,53225.806452,1.064516e+06
109,2023-02-01,1.83M,1830000.0,Kids_Diana_Show,28,65357.142857,1.307143e+06

In [ ]:
# Filter rows where the date is 2024-12-01
december_2024_rows = top_kids_monthly[top_kids_monthly['date'] == '2024-12-01']

# Display the filtered rows
december_2024_rows

Empty DataFrame
Columns: [date, estimation_earning, estimation_earning_numeric, youtuber, days_in_month, daily_average_earning, 20_day_earning]
Index: []