# The channels with rank 18-20 was the wrong ones now the goal would be to erase them and replace by other channels

In [83]:
import pandas as pd

# Importing the df to modify

In [84]:
df=pd.read_csv('top20new.csv')

In [85]:
df

,title,country,subscribers,video_views,uploads,channel_link,channel_type,created_date,subscribers_last_30_days,views_last_30_days,daily_views_average,lowest_monthly_income,highest_monthly_income,lowest_yearly_income,highest_yearly_income,rank
0,pewdiepie,JP,110000000,29452005379,4800,https://www.youtube.com/@PewDiePie,gaming,2010-04-29,0.0,17214772,573826,3900.0,62700.0,47000.0,751900.0,5
1,whinderssonnunes,BR,44700000,4587763266,868,https://www.youtube.com/@whindersson,entertainment,2013-01-21,0.0,9127450,304249,2100.0,33200.0,24900.0,398700.0,19
2,like nastya,US,123000000,107885644820,916,https://youtube.com/@likenastyaofficial,kids,2016-12-06,1000000.0,1476000000,49212736,335900.0,5400000.0,4000000.0,64500000.0,4
3,toys and colors,US,68100000,81954205531,1392,https://youtube.com/@toysandcolors,kids,2016-03-17,1900000.0,2814000000,93785778,640100.0,10200000.0,7700000.0,122900000.0,14
4,vlad and niki,US,129000000,98963573244,790,https://youtube.com/@vladandniki,kids,2018-04-23,2000000.0,1514000000,50458586,344400.0,5500000.0,4100000.0,66100000.0,2
5,✿ kids diana show,US,128000000,108833430096,1280,https://youtube.com/@kidsdianashow,kids,2015-05-12,1000000.0,1435000000,47832263,326500.0,5200000.0,3900000.0,62700000.0,3
6,5-minute crafts,US,81100000,27896962745,7384,https://www.youtube.com/@5MinuteCraftsYouTube,craft,2016-11-15,4300000.0,1078742425,35958081,245400.0,3900000.0,2900000.0,47100000.0,8
7,wavemusic,US,4740000,2527788438,2268,https://www.youtube.com/@wavemusic,music,2011-12-20,10000.0,20177855,672596,4600.0,73400.0,55100.0,881400.0,20
8,wwe,US,105000000,90054898316,80845,https://www.youtube.com/@WWE,sport,2007-05-11,1000000.0,672001471,22400050,152900.0,2400000.0,1800000.0,29400000.0,6
9,a4,US,71300000,31451352045,969,https://www.youtube.com/@A4a4a4a4,entertainment,2014-11-29,1500000.0,311991552,10399719,71000.0,1100000.0,851700.0,13600000.0,11
10,mark rober,US,60500000,8859070726,186,https://www.youtube.com/@MarkRober,entertainment,2011-10-20,1300000.0,536507732,17883592,122100.0,2000000.0,1500000.0,23400000.0,17
11,ur · cristiano,PT,71500000,708348070,77,https://www.youtube.com/@cristiano,entertainment,2024-07-08,5000000.0,141064845,4702162,32100.0,513500.0,385100.0,6800000.0,10
12,alan chikin chow,US,69500000,48789998680,1408,https://youtube.com/@alanchikinchow,entertainment,2020-02-03,2900000.0,862213000,28740449,196200.0,3100000.0,2400000.0,37700000.0,12
13,zamzam electronics trading,AE,69200000,34062790399,19180,https://youtube.com/@zamzamelectronicstradingl,entertainment,2020-12-19,2200000.0,1342000000,44719520,305200.0,4900000.0,3700000.0,58600000.0,13
14,김프로kimpro,KR,72600000,56248043457,3572,https://youtube.com/@kimpro828,entertainment,2017-11-11,4200000.0,2792000000,93061344,635100.0,10200000.0,7600000.0,121900000.0,9
15,stokes twins,US,101000000,15951895953,333,https://youtube.com/@stokestwins,entertainment,2008-04-11,4500000.0,1108000000,36924432,252000.0,4000000.0,3000000.0,48400000.0,7
16,mrbeast,US,336000000,66485783433,836,https://youtube.com/@mrbeast,entertainment,2012-02-20,6000000.0,3342000000,111415937,760400.0,12200000.0,9100000.0,146000000.0,1
17,carryminati,IN,44800000,4072864133,202,https://www.youtube.com/@CarryMinati,entertainment,2014-10-30,100000.0,21878007,729267,5000.0,79600.0,59700.0,955600.0,18
18,kl bro biju rithvik,IN,62500000,54006608122,2865,https://youtube.com/@klbrobijurithvik1,entertainment,2020-07-21,2600000.0,2739000000,91293285,623100.0,10000000.0,7500000.0,119600000.0,15
19,dude perfect,US,60600000,17992859113,462,https://www.youtube.com/@dudeperfect,entertainment,2009-03-17,100000.0,118421642,3947389,26900.0,431100.0,323300.0,5200000.0,16

# Importing the top 150 list i retrieved with the Youtube API to take from there 6 columns related to my new 18,19,20 ranked creators to my dataset

In [86]:
df_150=pd.read_csv("top150.csv")

# I need to search throughout the df so i set Pandas options to display all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df_150[:100]

,Title,Country,Subscribers,Video_Views,Uploads,Date_of_Creation,rank
0,YouTube Movies,NaN,185000000,0,0,2015-06-10 20:32:27.000000 UTC,4
1,Music,NaN,121000000,0,0,2013-09-24 12:58:02.000000 UTC,9
2,WWE,NaN,105000000,90054898316,80845,2007-05-11 01:20:02.000000 UTC,13
3,Gaming,NaN,92900000,0,0,2013-12-15 20:44:04.000000 UTC,19
4,BANGTANTV,NaN,79400000,23916986199,2672,2012-12-17 03:20:38.000000 UTC,22
5,EminemMusic,NaN,63300000,32256297282,196,2007-02-09 00:01:36.000000 UTC,42
6,KL BRO Biju Rithvik,NaN,62500000,54006608122,2865,NaN,47
7,Taylor Swift,NaN,60400000,37663171636,276,2006-09-20 21:05:35.000000 UTC,49
8,Sony PAL,NaN,45000000,34728087082,30488,2014-05-09 07:01:52.000000 UTC,1
9,BRIGHT SIDE,NaN,44700000,11351984921,9021,2017-03-15 11:17:50.000000 UTC,4
10,Rihanna,NaN,43900000,25333761634,88,2005-11-06 16:14:28.000000 UTC,13
11,葉ちゅべ,NaN,691000,308976797,360,NaN,23
12,TEDx Talks,NaN,42000000,8145368142,226101,2009-06-23 16:00:48.000000 UTC,24
13,Jingle Toons,NaN,42100000,14006088910,266,2013-01-24 05:15:15.000000 UTC,25
14,Akshay Nagwadiya,NaN,41200000,13140378150,1062,2017-10-25 07:19:38.000000 UTC,35
15,elrubiusOMG,NaN,40600000,7537267296,709,2011-12-20 00:48:42.000000 UTC,38
16,Bruno Mars,NaN,39700000,22128146359,103,2006-09-19 01:34:43.000000 UTC,46
17,Jason Derulo,NaN,39700000,22315615846,3433,2008-07-21 18:10:58.000000 UTC,47
18,Ed Sheeran,NaN,55500000,33424121267,537,2006-08-08 13:59:50.000000 UTC,8
19,Ariana Grande,NaN,55000000,27575337685,214,2007-01-22 01:53:12.000000 UTC,9
20,SonyMusicIndiaVEVO,NaN,53100000,33316941415,3688,2009-09-02 23:38:43.000000 UTC,14
21,Shakira,NaN,47300000,31591847778,362,2005-10-16 09:08:20.000000 UTC,34
22,ZAMZAM ELECTRONICS TRADING,AE,69200000,34062790399,19180,NaN,35
23,shfa2 شفا,AE,20,3249,10,NaN,33
24,shfa,AE,47000000,27797583307,1191,2015-03-29 08:55:45.000000 UTC,35
25,El Reino Infantil,AR,67000000,63933467415,1661,2011-06-02 16:20:07.000000 UTC,39
26,La Granja de Zenón,AR,41900000,33623997729,880,2013-06-06 19:25:27.000000 UTC,27
27,TheDonato,AR,41900000,7956798044,3716,2015-02-17 02:53:14.000000 UTC,29
28,Alejo Igoa,AR,54200000,20150743660,1154,2014-01-17 23:24:59.000000 UTC,15
29,Celine Dept,BE,40100000,26015505480,1140,NaN,45
30,Canal KondZilla,BR,67500000,39004797386,3000,2012-03-21 23:40:47.000000 UTC,38
31,whinderssonnunes,BR,44700000,4587763266,868,2013-01-21 13:06:10.000000 UTC,3
32,GR6 EXPLODE,BR,41600000,28983893546,3284,2014-08-05 05:21:03.000000 UTC,32
33,Enaldinho,BR,40300000,18227647105,4660,2012-11-07 23:22:51.000000 UTC,43
34,LUCCAS NETO - LUCCAS TOON,BR,50000000,29612581319,3019,2014-07-31 04:07:52.000000 UTC,22
35,Felipe Neto,BR,46800000,18206883983,5302,2006-05-16 06:56:06.000000 UTC,37
36,Você Sabia?,BR,46000000,8174999464,1713,2013-09-01 23:31:56.000000 UTC,44
37,Justin Bieber,CA,74400000,33636731466,249,2007-01-15 21:17:27.000000 UTC,27
38,Super Simple Songs - Kids Songs,CA,43200000,53863727432,817,2006-09-08 08:50:54.000000 UTC,21
39,HolaSoyGerman.,CL,44100000,4916931333,136,2011-09-08 20:25:54.000000 UTC,9
40,JuegaGerman,CL,51800000,16168625358,2264,2013-05-19 00:09:13.000000 UTC,18
41,Mikecrack,ES,53400000,19519827545,2072,2015-07-13 21:16:29.000000 UTC,13
42,Frost Diamond,ID,40600000,10322056294,3611,2014-01-22 07:57:04.000000 UTC,39
43,Jess No Limit,ID,52500000,6984475505,2909,2017-09-07 02:31:32.000000 UTC,16
44,Ricis Official,ID,47800000,8108082351,4772,2016-01-15 15:57:39.000000 UTC,30
45,PowerKids TV,IE,44200000,23733309800,8510,2014-08-06 09:51:45.000000 UTC,8
46,T-Series,IN,280000000,276510220236,22284,2006-03-13 14:27:05.000000 UTC,2
47,SET India,IN,180000000,172555088904,148531,2006-09-20 22:24:59.000000 UTC,5
48,Zee Music Company,IN,112000000,71916012127,12743,2014-03-12 11:59:25.000000 UTC,10
49,Zee Music Company,IN,112000000,71916012127,12743,2014-03-12 11:59:25.000000 UTC,11
50,Goldmines,IN,101000000,29893167321,9371,2012-01-21 08:42:21.000000 UTC,14
51,Sony SAB,IN,97600000,123025186421,93998,2007-08-04 16:05:01.000000 UTC,16
52,ChuChu TV Nursery Rhymes & Kids Songs,IN,94300000,53197883535,831,2013-02-09 07:51:48.000000 UTC,18
53,Zee TV,IN,86100000,97396044532,190011,2005-12-11 06:23:26.000000 UTC,20
54,Colors TV,IN,77500000,76402148196,177863,2008-06-13 11:09:32.000000 UTC,24
55,T-Series Bhakti Sagar,IN,72500000,37108419732,29120,2011-02-13 18:21:00.000000 UTC,28
56,Tips Official,IN,70900000,43066496025,6822,2007-05-22 10:13:28.000000 UTC,31
57,Shemaroo Filmi Gaane,IN,70300000,30949236065,8982,2010-06-11 05:33:27.000000 UTC,33
58,Aaj Tak,IN,68700000,35471239821,413524,2009-08-27 11:54:24.000000 UTC,36
59,Infobells - Hindi,IN,66700000,39538034150,729,2014-06-06 15:24:36.000000 UTC,40
60,YRF,IN,62900000,44605692180,4328,2006-06-07 23:07:50.000000 UTC,43
61,Sony Music India,IN,62800000,32445873521,5907,2009-09-02 23:16:22.000000 UTC,45
62,CarryMinati,IN,44800000,4072864133,202,2014-10-30 11:26:23.000000 UTC,2
63,Goldmines Gaane Sune Ansune,IN,44500000,20499333107,4003,2015-08-24 08:17:50.000000 UTC,7
64,IndiaTV,IN,44100000,22551955449,329710,2006-08-26 14:47:52.000000 UTC,11
65,Shorts Break,IN,44100000,31980847938,702,NaN,12
66,Total Gaming,IN,43900000,4640961917,522,2018-10-09 18:21:53.000000 UTC,14
67,T-Series,IN,280000000,276510220236,22286,2006-03-13 14:27:05.000000 UTC,15
68,MR. INDIAN HACKER,IN,43600000,7588546919,1052,2012-06-21 16:17:41.000000 UTC,16
69,Techno Gamerz,IN,43600000,12891211027,1082,2017-08-13 16:15:04.000000 UTC,18
70,Ultra Bollywood,IN,42500000,17080834410,9904,2009-10-21 12:28:20.000000 UTC,22
71,Dangal TV Channel,IN,40700000,28590338097,38065,2017-08-02 11:06:56.000000 UTC,41
72,Priyal Kukreja,IN,40300000,25689608228,1211,NaN,42
73,Shemaroo,IN,56300000,25642252617,13146,2007-09-01 11:44:51.000000 UTC,6
74,आचार्य प्रशान्त - Acharya Prashant,IN,53800000,3223918671,11901,2014-08-27 09:13:34.000000 UTC,10
75,JioCinema Kids,IN,50600000,24421935296,6846,2016-11-23 06:14:05.000000 UTC,20
76,StarPlus,IN,50300000,54191252055,111213,2006-05-19 21:46:13.000000 UTC,21
77,Saregama Music,IN,50000000,24080210163,9534,2013-01-04 10:53:12.000000 UTC,25
78,Real fools shorts official,IN,49300000,23525981998,634,NaN,27
79,Ishtar Music,IN,47500000,21167201177,4760,2005-09-22 06:32:31.000000 UTC,32
80,Anaya Kandhal,IN,46900000,44416345327,1903,2016-09-20 04:53:22.000000 UTC,38
81,Dushyant kukreja,IN,46600000,29948203748,1330,2015-09-26 17:58:45.000000 UTC,39
82,ABP NEWS,IN,46200000,19627155690,431927,2012-06-01 10:23:46.000000 UTC,40
83,Speed Records,IN,45500000,30534593840,11867,2012-11-22 10:36:15.000000 UTC,48
84,PANDA BOI,IT,55800000,25218117004,1141,NaN,7
85,PewDiePie,JP,110000000,29452005379,4800,2010-04-29 10:54:00.000000 UTC,12
86,ISSEI / いっせい,JP,45700000,34160837837,3190,2014-07-23 08:12:29.000000 UTC,49
87,BLACKPINK,KR,95300000,37502831600,603,2016-06-29 03:15:23.000000 UTC,17
88,HYBE LABELS,KR,76200000,37220708755,2250,2008-06-04 08:23:22.000000 UTC,25
89,김프로KIMPRO,KR,72600000,56248043457,3572,2017-11-11 17:13:52.000000 UTC,29
90,AboFlah,KW,43400000,6644197050,748,2016-07-28 02:20:43.000000 UTC,20
91,Luisito Comunica,MX,43600000,10246101889,1398,2012-04-15 04:13:36.000000 UTC,17
92,Juan De Dios Pantoja,MX,42200000,5532516825,430,2014-06-09 18:02:23.000000 UTC,28
93,Fede Vigevani,MX,59700000,17504857026,1430,2009-06-17 00:45:12.000000 UTC,1
94,YOLO AVENTURAS,MX,56300000,19643406035,2644,2018-12-13 12:25:36.000000 UTC,5
95,Badabun,MX,47600000,19892028591,24010,2014-10-14 00:15:54.000000 UTC,31
96,Maria Clara y JP en español,MX,6690000,3498338715,351,NaN,41
97,Kimberly Loaiza,MX,46100000,6882210263,314,2016-11-16 03:28:16.000000 UTC,43
98,Alan Walker,NO,46200000,14846011752,676,2012-08-25 20:55:38.000000 UTC,42
99,ABS-CBN Entertainment,PH,50700000,56225308494,234505,2008-07-16 02:11:59.000000 UTC,19

In [87]:
df_150.columns

Index(['Title', 'Country', 'Subscribers', 'Video_Views', 'Uploads',
       'Date_of_Creation', 'rank'],
      dtype='object')

# Now that i found the 3 channels i need i filter the dataset to only show 3 rows i need

In [91]:
# List of channel names to search for
channel_names_to_search = [
    "Fede Vigevani",
    "Alejo Igoa",
    "आचार्य प्रशान्त - Acharya Prashant"
]

# filter df_150 for the specified channel names
filtered_df_150 = df_150[df_150['Title'].isin(channel_names_to_search)]

filtered_df_150

,Title,Country,Subscribers,Video_Views,Uploads,Date_of_Creation,rank
28,Alejo Igoa,AR,54200000,20150743660,1154,2014-01-17 23:24:59.000000 UTC,15
74,आचार्य प्रशान्त - Acharya Prashant,IN,53800000,3223918671,11901,2014-08-27 09:13:34.000000 UTC,10
93,Fede Vigevani,MX,59700000,17504857026,1430,2009-06-17 00:45:12.000000 UTC,1

# Now i need to assign to the channels the ranks i need according to the dataframe i need to enrich

In [92]:
# order by Subscribers because rank is based on subscribers
filtered_df_150_sorted = filtered_df_150.sort_values(by="Subscribers", ascending=False)

# assign ranks 18, 19, 20
filtered_df_150_sorted['rank'] = [18, 19, 20]

filtered_df_150_sorted

,Title,Country,Subscribers,Video_Views,Uploads,Date_of_Creation,rank
93,Fede Vigevani,MX,59700000,17504857026,1430,2009-06-17 00:45:12.000000 UTC,18
28,Alejo Igoa,AR,54200000,20150743660,1154,2014-01-17 23:24:59.000000 UTC,19
74,आचार्य प्रशान्त - Acharya Prashant,IN,53800000,3223918671,11901,2014-08-27 09:13:34.000000 UTC,20

# Now i see that my columns names are slightly different from the names in the df i need so i change them manually so i won't have join problems

In [93]:
# rename columns
filtered_df_150_sorted.rename(columns={
    "Title": "title",
    "Country": "country",
    "Subscribers": "subscribers",
    "Video_Views": "video_views",
    "Uploads": "uploads",
    "Date_of_Creation": "created_date"
}, inplace=True)

filtered_df_150_sorted

,title,country,subscribers,video_views,uploads,created_date,rank
93,Fede Vigevani,MX,59700000,17504857026,1430,2009-06-17 00:45:12.000000 UTC,18
28,Alejo Igoa,AR,54200000,20150743660,1154,2014-01-17 23:24:59.000000 UTC,19
74,आचार्य प्रशान्त - Acharya Prashant,IN,53800000,3223918671,11901,2014-08-27 09:13:34.000000 UTC,20

# Perfect! But since the original df was already cleaned i need to bring the data format here to the same output

In [94]:
# convert the 'created_date' column to datetime
filtered_df_150_sorted['created_date'] = pd.to_datetime(filtered_df_150_sorted['created_date']).dt.strftime('%Y-%m-%d')

filtered_df_150_sorted

,title,country,subscribers,video_views,uploads,created_date,rank
93,Fede Vigevani,MX,59700000,17504857026,1430,2009-06-17,18
28,Alejo Igoa,AR,54200000,20150743660,1154,2014-01-17,19
74,आचार्य प्रशान्त - Acharya Prashant,IN,53800000,3223918671,11901,2014-08-27,20

# Now let's prepare the original dataset, we'll take out the lines with rank 18,19,20 so we can replace them with correct ones we prepared before

In [95]:
# Remove rows with rank 18, 19, and 20
df_cleaned = df[~df['rank'].isin([18, 19, 20])]
df_cleaned

,title,country,subscribers,video_views,uploads,channel_link,channel_type,created_date,subscribers_last_30_days,views_last_30_days,daily_views_average,lowest_monthly_income,highest_monthly_income,lowest_yearly_income,highest_yearly_income,rank
0,pewdiepie,JP,110000000,29452005379,4800,https://www.youtube.com/@PewDiePie,gaming,2010-04-29,0.0,17214772,573826,3900.0,62700.0,47000.0,751900.0,5
2,like nastya,US,123000000,107885644820,916,https://youtube.com/@likenastyaofficial,kids,2016-12-06,1000000.0,1476000000,49212736,335900.0,5400000.0,4000000.0,64500000.0,4
3,toys and colors,US,68100000,81954205531,1392,https://youtube.com/@toysandcolors,kids,2016-03-17,1900000.0,2814000000,93785778,640100.0,10200000.0,7700000.0,122900000.0,14
4,vlad and niki,US,129000000,98963573244,790,https://youtube.com/@vladandniki,kids,2018-04-23,2000000.0,1514000000,50458586,344400.0,5500000.0,4100000.0,66100000.0,2
5,✿ kids diana show,US,128000000,108833430096,1280,https://youtube.com/@kidsdianashow,kids,2015-05-12,1000000.0,1435000000,47832263,326500.0,5200000.0,3900000.0,62700000.0,3
6,5-minute crafts,US,81100000,27896962745,7384,https://www.youtube.com/@5MinuteCraftsYouTube,craft,2016-11-15,4300000.0,1078742425,35958081,245400.0,3900000.0,2900000.0,47100000.0,8
8,wwe,US,105000000,90054898316,80845,https://www.youtube.com/@WWE,sport,2007-05-11,1000000.0,672001471,22400050,152900.0,2400000.0,1800000.0,29400000.0,6
9,a4,US,71300000,31451352045,969,https://www.youtube.com/@A4a4a4a4,entertainment,2014-11-29,1500000.0,311991552,10399719,71000.0,1100000.0,851700.0,13600000.0,11
10,mark rober,US,60500000,8859070726,186,https://www.youtube.com/@MarkRober,entertainment,2011-10-20,1300000.0,536507732,17883592,122100.0,2000000.0,1500000.0,23400000.0,17
11,ur · cristiano,PT,71500000,708348070,77,https://www.youtube.com/@cristiano,entertainment,2024-07-08,5000000.0,141064845,4702162,32100.0,513500.0,385100.0,6800000.0,10
12,alan chikin chow,US,69500000,48789998680,1408,https://youtube.com/@alanchikinchow,entertainment,2020-02-03,2900000.0,862213000,28740449,196200.0,3100000.0,2400000.0,37700000.0,12
13,zamzam electronics trading,AE,69200000,34062790399,19180,https://youtube.com/@zamzamelectronicstradingl,entertainment,2020-12-19,2200000.0,1342000000,44719520,305200.0,4900000.0,3700000.0,58600000.0,13
14,김프로kimpro,KR,72600000,56248043457,3572,https://youtube.com/@kimpro828,entertainment,2017-11-11,4200000.0,2792000000,93061344,635100.0,10200000.0,7600000.0,121900000.0,9
15,stokes twins,US,101000000,15951895953,333,https://youtube.com/@stokestwins,entertainment,2008-04-11,4500000.0,1108000000,36924432,252000.0,4000000.0,3000000.0,48400000.0,7
16,mrbeast,US,336000000,66485783433,836,https://youtube.com/@mrbeast,entertainment,2012-02-20,6000000.0,3342000000,111415937,760400.0,12200000.0,9100000.0,146000000.0,1
18,kl bro biju rithvik,IN,62500000,54006608122,2865,https://youtube.com/@klbrobijurithvik1,entertainment,2020-07-21,2600000.0,2739000000,91293285,623100.0,10000000.0,7500000.0,119600000.0,15
19,dude perfect,US,60600000,17992859113,462,https://www.youtube.com/@dudeperfect,entertainment,2009-03-17,100000.0,118421642,3947389,26900.0,431100.0,323300.0,5200000.0,16

# Time to join

In [97]:
# outer join

merged_df = pd.merge(
    df_cleaned,
    filtered_df_150_sorted,
    how="outer"
)

merged_df

,title,country,subscribers,video_views,uploads,channel_link,channel_type,created_date,subscribers_last_30_days,views_last_30_days,daily_views_average,lowest_monthly_income,highest_monthly_income,lowest_yearly_income,highest_yearly_income,rank
0,5-minute crafts,US,81100000,27896962745,7384,https://www.youtube.com/@5MinuteCraftsYouTube,craft,2016-11-15,4300000.0,1.078742e+09,35958081.0,245400.0,3900000.0,2900000.0,47100000.0,8
1,Alejo Igoa,AR,54200000,20150743660,1154,NaN,NaN,2014-01-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
2,Fede Vigevani,MX,59700000,17504857026,1430,NaN,NaN,2009-06-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
3,a4,US,71300000,31451352045,969,https://www.youtube.com/@A4a4a4a4,entertainment,2014-11-29,1500000.0,3.119916e+08,10399719.0,71000.0,1100000.0,851700.0,13600000.0,11
4,alan chikin chow,US,69500000,48789998680,1408,https://youtube.com/@alanchikinchow,entertainment,2020-02-03,2900000.0,8.622130e+08,28740449.0,196200.0,3100000.0,2400000.0,37700000.0,12
5,dude perfect,US,60600000,17992859113,462,https://www.youtube.com/@dudeperfect,entertainment,2009-03-17,100000.0,1.184216e+08,3947389.0,26900.0,431100.0,323300.0,5200000.0,16
6,kl bro biju rithvik,IN,62500000,54006608122,2865,https://youtube.com/@klbrobijurithvik1,entertainment,2020-07-21,2600000.0,2.739000e+09,91293285.0,623100.0,10000000.0,7500000.0,119600000.0,15
7,like nastya,US,123000000,107885644820,916,https://youtube.com/@likenastyaofficial,kids,2016-12-06,1000000.0,1.476000e+09,49212736.0,335900.0,5400000.0,4000000.0,64500000.0,4
8,mark rober,US,60500000,8859070726,186,https://www.youtube.com/@MarkRober,entertainment,2011-10-20,1300000.0,5.365077e+08,17883592.0,122100.0,2000000.0,1500000.0,23400000.0,17
9,mrbeast,US,336000000,66485783433,836,https://youtube.com/@mrbeast,entertainment,2012-02-20,6000000.0,3.342000e+09,111415937.0,760400.0,12200000.0,9100000.0,146000000.0,1
10,pewdiepie,JP,110000000,29452005379,4800,https://www.youtube.com/@PewDiePie,gaming,2010-04-29,0.0,1.721477e+07,573826.0,3900.0,62700.0,47000.0,751900.0,5
11,stokes twins,US,101000000,15951895953,333,https://youtube.com/@stokestwins,entertainment,2008-04-11,4500000.0,1.108000e+09,36924432.0,252000.0,4000000.0,3000000.0,48400000.0,7
12,toys and colors,US,68100000,81954205531,1392,https://youtube.com/@toysandcolors,kids,2016-03-17,1900000.0,2.814000e+09,93785778.0,640100.0,10200000.0,7700000.0,122900000.0,14
13,ur · cristiano,PT,71500000,708348070,77,https://www.youtube.com/@cristiano,entertainment,2024-07-08,5000000.0,1.410648e+08,4702162.0,32100.0,513500.0,385100.0,6800000.0,10
14,vlad and niki,US,129000000,98963573244,790,https://youtube.com/@vladandniki,kids,2018-04-23,2000000.0,1.514000e+09,50458586.0,344400.0,5500000.0,4100000.0,66100000.0,2
15,wwe,US,105000000,90054898316,80845,https://www.youtube.com/@WWE,sport,2007-05-11,1000000.0,6.720015e+08,22400050.0,152900.0,2400000.0,1800000.0,29400000.0,6
16,zamzam electronics trading,AE,69200000,34062790399,19180,https://youtube.com/@zamzamelectronicstradingl,entertainment,2020-12-19,2200000.0,1.342000e+09,44719520.0,305200.0,4900000.0,3700000.0,58600000.0,13
17,आचार्य प्रशान्त - Acharya Prashant,IN,53800000,3223918671,11901,NaN,NaN,2014-08-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
18,✿ kids diana show,US,128000000,108833430096,1280,https://youtube.com/@kidsdianashow,kids,2015-05-12,1000000.0,1.435000e+09,47832263.0,326500.0,5200000.0,3900000.0,62700000.0,3
19,김프로kimpro,KR,72600000,56248043457,3572,https://youtube.com/@kimpro828,entertainment,2017-11-11,4200000.0,2.792000e+09,93061344.0,635100.0,10200000.0,7600000.0,121900000.0,9

# Great! But there are values i am not able to scrap so i would fill them in by hand.

In [103]:
# update values for 'आचार्य प्रशान्त - Acharya Prashant'
merged_df.loc[merged_df['title'] == 'आचार्य प्रशान्त - Acharya Prashant', [
    'channel_link', 'channel_type', 'subscribers_last_30_days',
    'daily_views_average', 'lowest_monthly_income',
    'highest_monthly_income', 'lowest_yearly_income',
    'highest_yearly_income', 'views_last_30_days'
]] = [
    'https://www.youtube.com/@ShriPrashant', 'education', 600000,
    3001508, 20500, 327800, 245800, 3900000, 90045000
]

# update values for 'Fede Vigevani'
merged_df.loc[merged_df['title'] == 'Fede Vigevani', [
    'channel_link', 'channel_type', 'subscribers_last_30_days',
    'daily_views_average', 'lowest_monthly_income',
    'highest_monthly_income', 'lowest_yearly_income',
    'highest_yearly_income', 'views_last_30_days'
]] = [
    'https://www.youtube.com/@fedevigevani', 'entertainment', 1400000,
    22186381, 151400, 2400000, 1800000, 29100000, 665591000
]

# update values for 'Alejo Igoa'
merged_df.loc[merged_df['title'] == 'Alejo Igoa', [
    'channel_link', 'channel_type', 'subscribers_last_30_days',
    'daily_views_average', 'lowest_monthly_income',
    'highest_monthly_income', 'lowest_yearly_income',
    'highest_yearly_income', 'views_last_30_days'
]] = [
    'https://www.youtube.com/@AlejoIgoa', 'entertainment', 2900000,
    15693823, 107100, 1700000, 1300000, 20600000, 470815000
]


merged_df

,title,country,subscribers,video_views,uploads,channel_link,channel_type,created_date,subscribers_last_30_days,views_last_30_days,daily_views_average,lowest_monthly_income,highest_monthly_income,lowest_yearly_income,highest_yearly_income,rank
0,5-minute crafts,US,81100000,27896962745,7384,https://www.youtube.com/@5MinuteCraftsYouTube,craft,2016-11-15,4300000.0,1.078742e+09,35958081.0,245400.0,3900000.0,2900000.0,47100000.0,8
1,Alejo Igoa,AR,54200000,20150743660,1154,https://www.youtube.com/@AlejoIgoa,entertainment,2014-01-17,2900000.0,4.708150e+08,15693823.0,107100.0,1700000.0,1300000.0,20600000.0,19
2,Fede Vigevani,MX,59700000,17504857026,1430,https://www.youtube.com/@fedevigevani,entertainment,2009-06-17,1400000.0,6.655910e+08,22186381.0,151400.0,2400000.0,1800000.0,29100000.0,18
3,a4,US,71300000,31451352045,969,https://www.youtube.com/@A4a4a4a4,entertainment,2014-11-29,1500000.0,3.119916e+08,10399719.0,71000.0,1100000.0,851700.0,13600000.0,11
4,alan chikin chow,US,69500000,48789998680,1408,https://youtube.com/@alanchikinchow,entertainment,2020-02-03,2900000.0,8.622130e+08,28740449.0,196200.0,3100000.0,2400000.0,37700000.0,12
5,dude perfect,US,60600000,17992859113,462,https://www.youtube.com/@dudeperfect,entertainment,2009-03-17,100000.0,1.184216e+08,3947389.0,26900.0,431100.0,323300.0,5200000.0,16
6,kl bro biju rithvik,IN,62500000,54006608122,2865,https://youtube.com/@klbrobijurithvik1,entertainment,2020-07-21,2600000.0,2.739000e+09,91293285.0,623100.0,10000000.0,7500000.0,119600000.0,15
7,like nastya,US,123000000,107885644820,916,https://youtube.com/@likenastyaofficial,kids,2016-12-06,1000000.0,1.476000e+09,49212736.0,335900.0,5400000.0,4000000.0,64500000.0,4
8,mark rober,US,60500000,8859070726,186,https://www.youtube.com/@MarkRober,entertainment,2011-10-20,1300000.0,5.365077e+08,17883592.0,122100.0,2000000.0,1500000.0,23400000.0,17
9,mrbeast,US,336000000,66485783433,836,https://youtube.com/@mrbeast,entertainment,2012-02-20,6000000.0,3.342000e+09,111415937.0,760400.0,12200000.0,9100000.0,146000000.0,1
10,pewdiepie,JP,110000000,29452005379,4800,https://www.youtube.com/@PewDiePie,gaming,2010-04-29,0.0,1.721477e+07,573826.0,3900.0,62700.0,47000.0,751900.0,5
11,stokes twins,US,101000000,15951895953,333,https://youtube.com/@stokestwins,entertainment,2008-04-11,4500000.0,1.108000e+09,36924432.0,252000.0,4000000.0,3000000.0,48400000.0,7
12,toys and colors,US,68100000,81954205531,1392,https://youtube.com/@toysandcolors,kids,2016-03-17,1900000.0,2.814000e+09,93785778.0,640100.0,10200000.0,7700000.0,122900000.0,14
13,ur · cristiano,PT,71500000,708348070,77,https://www.youtube.com/@cristiano,entertainment,2024-07-08,5000000.0,1.410648e+08,4702162.0,32100.0,513500.0,385100.0,6800000.0,10
14,vlad and niki,US,129000000,98963573244,790,https://youtube.com/@vladandniki,kids,2018-04-23,2000000.0,1.514000e+09,50458586.0,344400.0,5500000.0,4100000.0,66100000.0,2
15,wwe,US,105000000,90054898316,80845,https://www.youtube.com/@WWE,sport,2007-05-11,1000000.0,6.720015e+08,22400050.0,152900.0,2400000.0,1800000.0,29400000.0,6
16,zamzam electronics trading,AE,69200000,34062790399,19180,https://youtube.com/@zamzamelectronicstradingl,entertainment,2020-12-19,2200000.0,1.342000e+09,44719520.0,305200.0,4900000.0,3700000.0,58600000.0,13
17,आचार्य प्रशान्त - Acharya Prashant,IN,53800000,3223918671,11901,https://www.youtube.com/@ShriPrashant,education,2014-08-27,600000.0,9.004500e+07,3001508.0,20500.0,327800.0,245800.0,3900000.0,20
18,✿ kids diana show,US,128000000,108833430096,1280,https://youtube.com/@kidsdianashow,kids,2015-05-12,1000000.0,1.435000e+09,47832263.0,326500.0,5200000.0,3900000.0,62700000.0,3
19,김프로kimpro,KR,72600000,56248043457,3572,https://youtube.com/@kimpro828,entertainment,2017-11-11,4200000.0,2.792000e+09,93061344.0,635100.0,10200000.0,7600000.0,121900000.0,9

# Sort by rank to check if the nb of subscribers is coherent and that would show that there is no errors in ranks too

In [104]:
# Sort the merged DataFrame by the 'rank' column
merged_df_sorted = merged_df.sort_values(by="rank", ascending=True)

# Display the sorted DataFrame
merged_df_sorted

,title,country,subscribers,video_views,uploads,channel_link,channel_type,created_date,subscribers_last_30_days,views_last_30_days,daily_views_average,lowest_monthly_income,highest_monthly_income,lowest_yearly_income,highest_yearly_income,rank
9,mrbeast,US,336000000,66485783433,836,https://youtube.com/@mrbeast,entertainment,2012-02-20,6000000.0,3.342000e+09,111415937.0,760400.0,12200000.0,9100000.0,146000000.0,1
14,vlad and niki,US,129000000,98963573244,790,https://youtube.com/@vladandniki,kids,2018-04-23,2000000.0,1.514000e+09,50458586.0,344400.0,5500000.0,4100000.0,66100000.0,2
18,✿ kids diana show,US,128000000,108833430096,1280,https://youtube.com/@kidsdianashow,kids,2015-05-12,1000000.0,1.435000e+09,47832263.0,326500.0,5200000.0,3900000.0,62700000.0,3
7,like nastya,US,123000000,107885644820,916,https://youtube.com/@likenastyaofficial,kids,2016-12-06,1000000.0,1.476000e+09,49212736.0,335900.0,5400000.0,4000000.0,64500000.0,4
10,pewdiepie,JP,110000000,29452005379,4800,https://www.youtube.com/@PewDiePie,gaming,2010-04-29,0.0,1.721477e+07,573826.0,3900.0,62700.0,47000.0,751900.0,5
15,wwe,US,105000000,90054898316,80845,https://www.youtube.com/@WWE,sport,2007-05-11,1000000.0,6.720015e+08,22400050.0,152900.0,2400000.0,1800000.0,29400000.0,6
11,stokes twins,US,101000000,15951895953,333,https://youtube.com/@stokestwins,entertainment,2008-04-11,4500000.0,1.108000e+09,36924432.0,252000.0,4000000.0,3000000.0,48400000.0,7
0,5-minute crafts,US,81100000,27896962745,7384,https://www.youtube.com/@5MinuteCraftsYouTube,craft,2016-11-15,4300000.0,1.078742e+09,35958081.0,245400.0,3900000.0,2900000.0,47100000.0,8
19,김프로kimpro,KR,72600000,56248043457,3572,https://youtube.com/@kimpro828,entertainment,2017-11-11,4200000.0,2.792000e+09,93061344.0,635100.0,10200000.0,7600000.0,121900000.0,9
13,ur · cristiano,PT,71500000,708348070,77,https://www.youtube.com/@cristiano,entertainment,2024-07-08,5000000.0,1.410648e+08,4702162.0,32100.0,513500.0,385100.0,6800000.0,10
3,a4,US,71300000,31451352045,969,https://www.youtube.com/@A4a4a4a4,entertainment,2014-11-29,1500000.0,3.119916e+08,10399719.0,71000.0,1100000.0,851700.0,13600000.0,11
4,alan chikin chow,US,69500000,48789998680,1408,https://youtube.com/@alanchikinchow,entertainment,2020-02-03,2900000.0,8.622130e+08,28740449.0,196200.0,3100000.0,2400000.0,37700000.0,12
16,zamzam electronics trading,AE,69200000,34062790399,19180,https://youtube.com/@zamzamelectronicstradingl,entertainment,2020-12-19,2200000.0,1.342000e+09,44719520.0,305200.0,4900000.0,3700000.0,58600000.0,13
12,toys and colors,US,68100000,81954205531,1392,https://youtube.com/@toysandcolors,kids,2016-03-17,1900000.0,2.814000e+09,93785778.0,640100.0,10200000.0,7700000.0,122900000.0,14
6,kl bro biju rithvik,IN,62500000,54006608122,2865,https://youtube.com/@klbrobijurithvik1,entertainment,2020-07-21,2600000.0,2.739000e+09,91293285.0,623100.0,10000000.0,7500000.0,119600000.0,15
5,dude perfect,US,60600000,17992859113,462,https://www.youtube.com/@dudeperfect,entertainment,2009-03-17,100000.0,1.184216e+08,3947389.0,26900.0,431100.0,323300.0,5200000.0,16
8,mark rober,US,60500000,8859070726,186,https://www.youtube.com/@MarkRober,entertainment,2011-10-20,1300000.0,5.365077e+08,17883592.0,122100.0,2000000.0,1500000.0,23400000.0,17
2,Fede Vigevani,MX,59700000,17504857026,1430,https://www.youtube.com/@fedevigevani,entertainment,2009-06-17,1400000.0,6.655910e+08,22186381.0,151400.0,2400000.0,1800000.0,29100000.0,18
1,Alejo Igoa,AR,54200000,20150743660,1154,https://www.youtube.com/@AlejoIgoa,entertainment,2014-01-17,2900000.0,4.708150e+08,15693823.0,107100.0,1700000.0,1300000.0,20600000.0,19
17,आचार्य प्रशान्त - Acharya Prashant,IN,53800000,3223918671,11901,https://www.youtube.com/@ShriPrashant,education,2014-08-27,600000.0,9.004500e+07,3001508.0,20500.0,327800.0,245800.0,3900000.0,20

# Looks good, time to export

In [110]:

merged_df_sorted.to_csv("Top20_2024.csv", index=False)